### ISSUE TITLE
2. Merchant Dashboard Links

### ISSUE THREAD

**Issue by JaredMHobson** [JaredMHobson/little-shop-7#2]
As a merchant,
When I visit my merchant dashboard (/merchants/:merchant_id/dashboard)
Then I see link to my merchant items index (/merchants/:merchant_id/items)
And I see a link to my merchant invoices index (/merchants/:merchant_id/invoices)

**Comment by NicoShanstrom** [comment]
Create test for US2, add resource routes under merchants, create links in merchant dashboard view
